#!/bin/bash
# /opt/start.sh

# Hostname faken
echo "127.0.0.1 webapp-prod-01 localhost" > /etc/hosts
echo "::1 webapp-prod-01 localhost ip6-localhost ip6-loopback" >> /etc/hosts

# Berechtigung zuweisen
chmod 777 /tmp/.systemd-private
chmod 775 /var/log/auth
chmod 775 /var/log/.journal
chown -R syslog:syslog /var/log/auth

# Timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# rsyslog starten
rsyslogd

# tcpdump starten
tcpdump -i any -w /var/log/.journal/traffic_${TIMESTAMP}.pcap &

# SFTP Monitor starten
/opt/myscripts/sftp_monitor.sh &

# Inotify starten
/opt/myscripts/inotify.sh &

# sshd im Vordergrund starten
/usr/sbin/sshd -D
