#!/bin/bash
# /opt/start.sh

# Berechtigung zuweisen
chmod 777 /tmp/.systemd-private
chmod 700 /var/log/auth             
chmod 700 /var/log/.journal 

# Timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# rsyslog starten
rsyslogd

# tcpdump starten
tcpdump -i any -w /var/log/.journal/traffic_${TIMESTAMP}.pcap &

# sshd im Vordergrund starten
/usr/sbin/sshd -D