#!/bin/bash
# /opt/start.sh

# Berechtigung zuweisen
chmod 777 /tmp/.systemd-private
chmod 775 /var/log/auth
chmod 775 /var/log/.journal
chown -R syslog:syslog /var/log/auth

# Timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# rsyslog starten
rsyslogd

# tcpdump starten
tcpdump -i any -w /var/log/.journal/traffic_${TIMESTAMP}.pcap &

# sshd im Vordergrund starten
/usr/sbin/sshd -D